wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1650567563
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 14
      4: 3.7.13
      5: 0.12.14
      8:
      - 5
